language: clojure

jdk:
- oraclejdk7
- oraclejdk8

install:
  - curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > $HOME/lein
  - chmod u+x $HOME/lein
  - export lein=$HOME/lein

script: $lein with-profile +web-war do test, build

before_deploy:
  - export VERSION=$(printf $(cat VERSION))
  - chmod +x .travis/build-releases.sh
  - .travis/build-releases.sh

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file:
    - "releases/featured-$VERSION-standalone.jar"
    - "releases/featured-$VERSION-web.jar"
    - "releases/featured-$VERSION.war"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk7

cache:
  directories:
    - $HOME/.m2
    - $HOME/.lein
