language: clojure
sudo: required

branches:
  only:
    - master
    - /^release-.*$/
    - docker_image

addons:
  postgresql: "9.4"

jdk:
  - oraclejdk8

services:
  - postgresql
  - docker

install:
  - curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > $HOME/lein
  - chmod u+x $HOME/lein
  - export lein=$HOME/lein

before_script:
  - psql -c 'create database pdok;' -U postgres
  - psql -U postgres -d pdok -c "create extension postgis"
  - psql -U postgres -d pdok -c "CREATE EXTENSION postgis_topology;"
  - psql -U postgres -d pdok  -c "CREATE EXTENSION fuzzystrmatch"
  - psql -U postgres -d pdok -c "CREATE EXTENSION postgis_tiger_geocoder;"
  - export PROCESSOR_DATABASE_PASSWORD=
  - export DATA_DATABASE_PASSWORD=
  - export EXTRACTS_DATABASE_PASSWORD=

script:
  - $lein test
  - $lein test :regression
  - $lein with-profile +web-jar build

after_script:
  - chmod +x .travis/create-docker*snapshot.sh
  - .travis/create-docker-cli-snapshot.sh
  - .travis/create-docker-web-snapshot.sh

before_deploy:
  - export VERSION=$(printf $(cat VERSION))
  - chmod +x .travis/*.sh
  - .travis/build-releases.sh

deploy:
  - provider: script
    script: .travis/create-docker-cli-release.sh
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: .travis/create-docker-web-release.sh
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file:
      - releases/featured-$VERSION-standalone.jar
      - releases/featured-$VERSION-web.jar
      - releases/featured-$VERSION.war
    skip_cleanup: true
    on:
      tags: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.lein
